package org.opendatamesh.notification;

public enum EventType {
    DATA_PRODUCT_CREATED,
    DATA_PRODUCT_UPDATED,
    DATA_PRODUCT_DELETED,
    DATA_PRODUCT_VERSION_CREATED,
    DATA_PRODUCT_VERSION_DELETED
}
