-- Fix foreign key constraint to allow CASCADE delete for policy engines
ALTER TABLE "ODMPOLICY"."POLICIES" DROP CONSTRAINT "C_FK1__POLICIES";
ALTER TABLE "ODMPOLICY"."POLICIES" ADD CONSTRAINT "C_FK1__POLICIES" FOREIGN KEY("POLICY_ENGINE_ID") REFERENCES "ODMPOLICY"."POLICY_ENGINES"("ID") ON DELETE CASCADE;