-- Drop the old NO-ACTION FK (no IF EXISTS in MySQL)
ALTER TABLE NOTIFICATIONS
  DROP FOREIGN KEY C_FK1__NOTIFICATIONS;

-- Add back with ON DELETE CASCADE
ALTER TABLE NOTIFICATIONS
  ADD CONSTRAINT C_FK1__NOTIFICATIONS
    FOREIGN KEY (OBSERVER_ID)
    REFERENCES ODMNOTIFICATION.OBSERVERS(ID)
    ON DELETE CASCADE;