-- MySql 8;

CREATE TABLE hibernate_sequence (
    NEXT_VAL BIGINT AUTO_INCREMENT,
    PRIMARY KEY (NEXT_VAL)
);
INSERT INTO hibernate_sequence VALUES (0);


-- DATA_PRODUCTS

CREATE TABLE DATA_PRODUCTS(
    ID  VARCHAR(255) PRIMARY KEY,
    FQN  VARCHAR(255),
    DOMAIN  VARCHAR(255),
    DESCRIPTION  VARCHAR(255)    
);


-- DATA PPRODUCT > VERSIONS

CREATE TABLE DP_VERSIONS(  
    DATA_PRODUCT_ID  VARCHAR(255) NOT NULL,
    VERSION_NUMBER  VARCHAR(255) NOT NULL,

    DP_FQN  VARCHAR(255),
    DP_ENTITY_TYPE  VARCHAR(255),
    DP_NAME  VARCHAR(255),
    DP_DISPLAY_NAME  VARCHAR(255),
    DP_DOMAIN  VARCHAR(255),
    
    DESCRIPTION  VARCHAR(255),
    OWNER_ID  VARCHAR(255) NOT NULL
    EXTERNAL_DOC_ID BIGINT,

    DPDS_VERSION  VARCHAR(255),
    CONTENT  VARCHAR(5000),
    
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);
ALTER TABLE DP_VERSIONS ADD CONSTRAINT C_PK_DP_VERSIONS PRIMARY KEY (DATA_PRODUCT_ID, VERSION_NUMBER);


-- DATA PPRODUCT > VERSION > INFO_OWNERS

CREATE TABLE DPV_INFO_OWNERS(
    ID  VARCHAR(255) PRIMARY KEY,
    NAME  VARCHAR(255)
);


-- DATA PPRODUCT > VERSION > INFO_CONTACT_POINTS

CREATE TABLE DPV_INFO_CONTACT_POINTS(
    DATA_PRODUCT_ID  VARCHAR(255) NOT NULL,
    VERSION_NUMBER  VARCHAR(255) NOT NULL,
    NAME  VARCHAR(255),
    DESCRIPTION  VARCHAR(255),
    CHANNEL  VARCHAR(255),
    ADDRESS  VARCHAR(255)
);

-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENTS

CREATE TABLE DPDS_PORTS(
    DATA_PRODUCT_ID  VARCHAR(255),
    DATA_PRODUCT_VERSION  VARCHAR(255),

    ID  VARCHAR(255) PRIMARY KEY,
    FQN  VARCHAR(255),
    ENTITY_TYPE  VARCHAR(255),
    NAME  VARCHAR(255),
    VERSION  VARCHAR(255),

    DESCRIPTION  VARCHAR(255),
    DISPLAY_NAME  VARCHAR(255),
    
    PROMISES_ID BIGINT,
    EXPECTATIONS_ID BIGINT,
    CONTRACTS_ID BIGINT,
    
    COMPONENT_GROUP  VARCHAR(255),
    EXTERNAL_DOC_ID BIGINT,

    CONTENT  VARCHAR(5000),
    
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENTS

CREATE TABLE DPV_APP_COMPONENTS(
    DATA_PRODUCT_ID  VARCHAR(255),
    DATA_PRODUCT_VERSION  VARCHAR(255),

    ID  VARCHAR(255) PRIMARY KEY,
    FQN  VARCHAR(255),
    ENTITY_TYPE  VARCHAR(255),
    NAME  VARCHAR(255),
    VERSION  VARCHAR(255),
    
    DISPLAY_NAME  VARCHAR(255),
    DESCRIPTION  VARCHAR(255),
    
    APPLICATION_TYPE  VARCHAR(255),
    PLATFORM  VARCHAR(255),

    BUILD_INFO_ID BIGINT,
    DEPLOY_INFO_ID BIGINT,
    
    COMPONENT_GROUP  VARCHAR(255),
    EXTERNAL_DOC_ID BIGINT,
    
    CONTENT  VARCHAR(5000),
    
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);


-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENT_DEPENDENCIES

CREATE TABLE DPV_APP_COMPONENT_DEPENDENCIES(
    COMPONENT_ID  VARCHAR(255) NOT NULL,
    DEPENDS_ON_COMPONENT_ID  VARCHAR(255)
);


-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENTS

CREATE TABLE DPV_INFRA_COMPONENTS(
    DATA_PRODUCT_ID  VARCHAR(255),
    DATA_PRODUCT_VERSION  VARCHAR(255),

    ID  VARCHAR(255) PRIMARY KEY,
    FQN  VARCHAR(255),
    ENTITY_TYPE  VARCHAR(255),
    NAME  VARCHAR(255),
    VERSION  VARCHAR(255),

    DESCRIPTION  VARCHAR(255),
    DISPLAY_NAME  VARCHAR(255),
    
    INFRASTRUCTURE_TYPE  VARCHAR(255),
    PLATFORM  VARCHAR(255),
    
    PROVISION_INFO_ID BIGINT,
        
    COMPONENT_GROUP  VARCHAR(255),
    EXTERNAL_DOC_ID BIGINT,
   
    CONTENT  VARCHAR(5000),

    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP
);

-- DATA PPRODUCT > VERSION > DPV_INFRA_COMPONENT_DEPENDENCIES

CREATE TABLE DPV_INFRA_COMPONENT_DEPENDENCIES(
    COMPONENT_ID  VARCHAR(255) NOT NULL,
    DEPENDS_ON_COMPONENT_ID  VARCHAR(255)
);







CREATE TABLE DPDS_APP_COMPONENT_BUILD_INFOS(
    ID BIGINT PRIMARY KEY,
    CONFIGURATIONS VARCHAR(5000),
    SERVICE_ID BIGINT,
    TEMPLATE_ID BIGINT
);

CREATE TABLE DPDS_APP_COMPONENT_DEPLOY_INFOS(
    ID BIGINT PRIMARY KEY,
    CONFIGURATIONS  VARCHAR(5000),
    SERVICE_ID BIGINT,
    TEMPLATE_ID BIGINT
);

CREATE TABLE DPDS_APP_COMPONENT_SINKS(
    ID  VARCHAR(255) NOT NULL,
    SINK_ID  VARCHAR(255)
);

CREATE TABLE DPDS_APP_COMPONENT_SOURCES(
    ID  VARCHAR(255) NOT NULL,
    SOURCE_ID  VARCHAR(255)
);

CREATE TABLE DPDS_APP_COMPONENT_TAGS(
    ID  VARCHAR(255) NOT NULL,
    TAG_ID  VARCHAR(255)
);



CREATE TABLE DPDS_DATA_PRODUCT_TAGS(
    DATAPRODUCT_ID  VARCHAR(255) NOT NULL,
    VERSION  VARCHAR(255) NOT NULL,
    TAG_ID  VARCHAR(255)
);



CREATE TABLE DPDS_EXTERNAL_RESOURCES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(255),
    HREF  VARCHAR(255),
    MEDIA_TYPE  VARCHAR(255),
    PRIMARY KEY (ID)
);







CREATE TABLE DPDS_INFRA_COMPONENT_TAGS(
    ID  VARCHAR(255) NOT NULL,
    TAG_ID  VARCHAR(255)
);



CREATE TABLE DPDS_INFRA_PROVISION_INFOS(
    ID BIGINT PRIMARY KEY,
    CONFIGURATIONS  VARCHAR(5000),
    SERVICE_ID BIGINT,
    TEMPLATE_ID BIGINT
);

CREATE TABLE DPDS_PORT_CONTRACTS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BILLING_POLICY_ID BIGINT,
    SLA_ID BIGINT,
    TERMS_AND_CONDITIONS_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_PORT_EXPECTATIONS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    AUDIENCE_ID BIGINT,
    USAGE_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_PORT_PROMISES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    API_ID BIGINT,
    PLATFORM  VARCHAR(255),
    SERVICE_TYPE  VARCHAR(255),
    DEPRECTAION_POLICY_ID BIGINT,
    SLO_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_PORT_TAGS(
    ID  VARCHAR(255) NOT NULL,
    TAG_ID  VARCHAR(255)
);



CREATE TABLE DPDS_REFERENCE_OBJECTS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(255),
    ORIGINAL_REF  VARCHAR(255),
    CONTENT  VARCHAR(5000),
    REF  VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_SPEC_EXTENSION_POINTS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(255),
    EXTERNAL_DOC_ID BIGINT,
    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_STANDARD_DEFINITIONS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    VERSION  VARCHAR(50),
    DESCRIPTION  VARCHAR(255),
    SPECIFICATION  VARCHAR(255),
    SPECIFICATION_VERSION VARCHAR(50),
    DEFINITION_ID BIGINT, -- FK on DPDS_EXTERNAL_RESOURCES(ID)
    EXTERNAL_DOC_ID BIGINT, -- FK on DPDS_REFERENCE_OBJECTS(ID)

    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_DEFINITIONS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    VERSION  VARCHAR(50),
    STATUS VARCHAR(125),
    DISPLAY_NAME VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    TYPE VARCHAR(255),
    SPECIFICATION VARCHAR(255),
    SPECIFICATION_VERSION VARCHAR(50),
    CONTENT_MEDIA_TYPE VARCHAR(255),
    CONTENT VARCHAR(5000),

    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_TEMPLATE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DESCRIPTION  VARCHAR(255),
    HREF  VARCHAR(255),
    MEDIA_TYPE  VARCHAR(255),

    PRIMARY KEY (ID)
);

CREATE TABLE DPDS_COMPONENT_TEMPLATE(
    COMPONENT_ID VARCHAR(255) NOT NULL,
    TEMPLATE_ID BIGINT NOT NULL,
    COMPONENT_TYPE VARCHAR(255) NOT NULL,
    INFO_TYPE VARCHAR(255) NOT NULL
)
ALTER TABLE DPDS_COMPONENT_TEMPLATE ADD CONSTRAINT DPDS_COMPONENT_TEMPLATE_PK PRIMARY KEY (COMPONENT_ID, TEMPLATE_ID, COMPONENT_TYPE, INFO_TYPE);


CREATE TABLE DPDS_SCHEMAS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    VERSION VARCHAR(50) NOT NULL,
    MEDIA_TYPE VARCHAR(255),
    CONTENT VARCHAR(5000)
)
ALTER TABLE DPDS_SCHEMAS ADD CONSTRAINT DPDS_SCHEMAS_PK PRIMARY KEY (ID);

CREATE TABLE DPDS_API_TO_SCHEMA_RELATIONSHIPS(
    API_ID BIGINT NOT NULL,
    SCHEMA_ID BIGINT NOT NULL,
    OPERATION_ID VARCHAR(255),
    OUTPUT_MEDIA_TYPE VARCHAR(255),
)
ALTER TABLE DPDS_API_TO_SCHEMA_RELATIONSHIPS ADD CONSTRAINT DPDS_API_TO_SCHEMA_RELATIONSHIPS_PK PRIMARY KEY (API_ID, SCHEMA_ID);
-- TODO ADD FK


-- FKs

ALTER TABLE DP_VERSIONS ADD CONSTRAINT C_FK1_DP_VERSIONS FOREIGN KEY(OWNER_ID) REFERENCES DPV_INFO_OWNERS(ID);
ALTER TABLE DP_VERSIONS ADD CONSTRAINT C_FK2_DP_VERSIONS FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);

ALTER TABLE DPV_INFO_CONTACT_POINTS ADD CONSTRAINT C_FK_DPV_INFO_CONTACT_POINTS FOREIGN KEY(DATA_PRODUCT_ID, VERSION_NUMBER) REFERENCES DP_VERSIONS(DATA_PRODUCT_ID, VERSION_NUMBER);
ALTER TABLE DPDS_PORTS ADD CONSTRAINT C_FK_PORTS FOREIGN KEY(DATA_PRODUCT_ID, VERSION) REFERENCES DP_VERSIONS(DATA_PRODUCT_ID, VERSION_NUMBER);

ALTER TABLE DPDS_DATA_PRODUCT_TAGS ADD CONSTRAINT C_FK_DATA_PRODUCT_TAGS FOREIGN KEY(DATAPRODUCT_ID, VERSION) REFERENCES DP_VERSIONS(DATA_PRODUCT_ID, VERSION_NUMBER);

-- DPV_APP_COMPONENTS FKs

ALTER TABLE DPV_APP_COMPONENTS ADD CONSTRAINT C_FK1_DPV_APP_COMPONENTS FOREIGN KEY(DATA_PRODUCT_ID, DATA_PRODUCT_VERSION) REFERENCES DP_VERSIONS(DATA_PRODUCT_ID, VERSION_NUMBER);
ALTER TABLE DPV_APP_COMPONENTS ADD CONSTRAINT C_FK2_DPV_APP_COMPONENTS FOREIGN KEY(BUILD_INFO_ID) REFERENCES DPDS_APP_COMPONENT_BUILD_INFOS(ID);
ALTER TABLE DPV_APP_COMPONENTS ADD CONSTRAINT C_FK3_DPV_APP_COMPONENTS FOREIGN KEY(DEPLOY_INFO_ID) REFERENCES DPDS_APP_COMPONENT_DEPLOY_INFOS(ID);
ALTER TABLE DPV_APP_COMPONENTS ADD CONSTRAINT C_FK4_DPV_APP_COMPONENTS FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);

ALTER TABLE DPV_APP_COMPONENT_DEPENDENCIES ADD CONSTRAINT C_FK_DPV_APP_COMPONENT_DEPENDENCIES FOREIGN KEY(COMPONENT_ID) REFERENCES DPV_APP_COMPONENTS(ID);
ALTER TABLE DPDS_APP_COMPONENT_TAGS ADD CONSTRAINT FKSQ1G1IFWKXGV440A0HOKR1LEU FOREIGN KEY(ID) REFERENCES DPV_APP_COMPONENTS(ID);

-- DPV_APP_COMPONENTS FKs
ALTER TABLE DPV_INFRA_COMPONENTS ADD CONSTRAINT C_FK1_DPV_INFRA_COMPONENTS FOREIGN KEY(DATA_PRODUCT_ID, DATA_PRODUCT_VERSION) REFERENCES DP_VERSIONS(DATA_PRODUCT_ID, VERSION_NUMBER);
ALTER TABLE DPV_INFRA_COMPONENTS ADD CONSTRAINT C_FK2_DPV_INFRA_COMPONENTS FOREIGN KEY(PROVISION_INFO_ID) REFERENCES DPDS_INFRA_PROVISION_INFOS(ID);
ALTER TABLE DPV_INFRA_COMPONENTS ADD CONSTRAINT C_FK3_DPV_INFRA_COMPONENTS FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);


ALTER TABLE DPV_INFRA_COMPONENT_DEPENDENCIES ADD CONSTRAINT C_FK_DPV_INFRA_COMPONENT_DEPENDENCIES FOREIGN KEY(COMPONENT_ID) REFERENCES DPV_INFRA_COMPONENTS(ID);
ALTER TABLE DPDS_INFRA_COMPONENT_TAGS ADD CONSTRAINT FKOGCUHXRVBR8TRJSNF1SCFJK0D FOREIGN KEY(ID) REFERENCES DPV_INFRA_COMPONENTS(ID);


-- TODOs


ALTER TABLE DPDS_APP_COMPONENT_SINKS ADD CONSTRAINT FKQE422CLVRRG8J0GXLDRV4IW6V FOREIGN KEY(ID) REFERENCES DPV_APP_COMPONENTS(ID);
ALTER TABLE DPDS_APP_COMPONENT_SOURCES ADD CONSTRAINT FKR33DO8116KIGTE5LYMDB8I1TP FOREIGN KEY(ID) REFERENCES DPV_APP_COMPONENTS(ID);


ALTER TABLE DPDS_PORT_EXPECTATIONS ADD CONSTRAINT FK6OUWT8NGHLS5VGDJMJGNHW76T FOREIGN KEY(AUDIENCE_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);
ALTER TABLE DPDS_PORT_PROMISES ADD CONSTRAINT FKWP3UH6EAAQGP6G9L2E54J8S3 FOREIGN KEY(SLO_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);



ALTER TABLE DPDS_PORT_PROMISES ADD CONSTRAINT FKTDT2R73RTCJ1SN6GIIQY3G3RP FOREIGN KEY(DEPRECTAION_POLICY_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);
ALTER TABLE DPDS_SPEC_EXTENSION_POINTS ADD CONSTRAINT FK9FJQQ2L7NR7TAXI81TU5J4LBW FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);
ALTER TABLE DPDS_PORT_EXPECTATIONS ADD CONSTRAINT FK47C01XXKCY2X9N9QOY3EK0JLD FOREIGN KEY(USAGE_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);

ALTER TABLE DPDS_PORTS ADD CONSTRAINT FKDW3KFLV5SXMUSKX8QFH6J2KQ8 FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);


ALTER TABLE DPDS_STANDARD_DEFINITIONS ADD CONSTRAINT FKN28C6VYQCY0S460D5WB2VO4R0 FOREIGN KEY(EXTERNAL_DOC_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);
ALTER TABLE DPDS_PORT_TAGS ADD CONSTRAINT FKSXD77OQ8WIO381WHOJWICLXLG FOREIGN KEY(ID) REFERENCES DPDS_PORTS(ID);
ALTER TABLE DPDS_APP_COMPONENT_BUILD_INFOS ADD CONSTRAINT FKA97KW9AILVD4E74LC7TJXNDGL FOREIGN KEY(SERVICE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);
ALTER TABLE DPDS_INFRA_PROVISION_INFOS ADD CONSTRAINT FKM7I22E0X3P84YSYUC0525LGC0 FOREIGN KEY(TEMPLATE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);

ALTER TABLE DPDS_PORT_CONTRACTS ADD CONSTRAINT FK9DAAXC2S6VM3M6G30EV1F0U8S FOREIGN KEY(SLA_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);
ALTER TABLE DPDS_APP_COMPONENT_BUILD_INFOS ADD CONSTRAINT FKLU60VQDNDN350990MQ19DAAIF FOREIGN KEY(TEMPLATE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);


ALTER TABLE DPDS_INFRA_PROVISION_INFOS ADD CONSTRAINT FKOEXPXBDNEG1J0K1252FLJGR0D FOREIGN KEY(SERVICE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);
ALTER TABLE DPDS_PORTS ADD CONSTRAINT FK2SKEW7RDMXDMNXQW1O3RRD7NA FOREIGN KEY(EXPECTATIONS_ID) REFERENCES DPDS_PORT_EXPECTATIONS(ID);
ALTER TABLE DPDS_PORTS ADD CONSTRAINT FKIH1DEC2JNXAPG185SX15N334I FOREIGN KEY(PROMISES_ID) REFERENCES DPDS_PORT_PROMISES(ID);
ALTER TABLE DPDS_PORTS ADD CONSTRAINT FKD9WUAB4HK5HFJ12BP2BDRDENU FOREIGN KEY(CONTRACTS_ID) REFERENCES DPDS_PORT_CONTRACTS(ID);


ALTER TABLE DPDS_STANDARD_DEFINITIONS ADD CONSTRAINT FKRKJVHRTXR6P31WQBO399FCE26 FOREIGN KEY(DEFINITION_ID) REFERENCES DPDS_REFERENCE_OBJECTS(ID);

ALTER TABLE DPDS_PORT_CONTRACTS ADD CONSTRAINT FKR2XMY5Q0CTMMQ301KNVHVFQH8 FOREIGN KEY(BILLING_POLICY_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);



ALTER TABLE DPDS_PORT_CONTRACTS ADD CONSTRAINT FK48OOYF319R9RSVKK9FRW4X7GG FOREIGN KEY(TERMS_AND_CONDITIONS_ID) REFERENCES DPDS_SPEC_EXTENSION_POINTS(ID);
ALTER TABLE DPDS_APP_COMPONENT_DEPLOY_INFOS ADD CONSTRAINT FKTPC0GAMBVQKQK8E3DKRW8R24A FOREIGN KEY(TEMPLATE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);

ALTER TABLE DPDS_APP_COMPONENT_DEPLOY_INFOS ADD CONSTRAINT FK8VI9YWFKJOOYEL3URUJICOOK9 FOREIGN KEY(SERVICE_ID) REFERENCES DPDS_EXTERNAL_RESOURCES(ID);


ALTER TABLE DPDS_COMPONENT_TEMPLATE ADD CONSTRAINT CONSTRAINT_DPDS_COMPONENT_TEMPLATE_FK2 FOREIGN KEY(TEMPLATE_ID) REFERENCES DPDS_TEMPLATE(ID);