##########################
# Spring profile
##########################
spring:
  profiles:
    #active: ${SPRING_PROFILES_ACTIVE}
    active: dev

# @note Set spring profiles adding ENV variable SPRING_PROFILES_ACTIVE to run configurations

##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: /api/v1/pp/

##########################
# Logging configuration
##########################
logging:
  level:
    org:
      apache:
        http: INFO
      opendatamesh:
        platform:
          pp:
            api.*: DEBUG
    httpclient:
      wire: INFO
      

##########################
# Doc configuration
##########################
springdoc:
  swagger-ui:
    operationsSorter: alpha

# @see https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/


##########################
# Other configuration
##########################
skippolicyservice: true
skipmetaservice: true


