##########################
# Logging configuration
##########################
logging:
  level:
    org:
      apache:
        http: INFO
      opendatamesh:
        dpexperience:
          api.*: DEBUG
    httpclient:
      wire: INFO
    it:
      quantyca:
        odm:
          api:
            planes:
              dpexperience.*: DEBUG

##########################
# Other configuration
##########################
skippolicyservice: true
skipmetaservice: true
#For sorting endpoints alphabetically
springdoc:
  swagger-ui:
    operationsSorter: alpha

##########################
# Active profile
##########################
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
# Set spring profiles adding ENV variable SPRING_PROFILES_ACTIVE to run configurations