-- 1. Drop the old NO-ACTION FK
ALTER TABLE "ODMNOTIFICATION"."NOTIFICATIONS"
  DROP CONSTRAINT IF EXISTS "C_FK1__NOTIFICATIONS";

-- 2. Add it back with ON DELETE CASCADE
ALTER TABLE "ODMNOTIFICATION"."NOTIFICATIONS"
  ADD CONSTRAINT "C_FK1__NOTIFICATIONS"
    FOREIGN KEY ("OBSERVER_ID")
    REFERENCES "ODMNOTIFICATION"."OBSERVERS"("ID")
    ON DELETE CASCADE;
