##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 9002
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/metaservice/

############################################
# Spring configurations
############################################

spring:
  # Profile
  profile: dev
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: none
      #show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        schemas: ODMNOTIFICATION
    database-platform: org.hibernate.dialect.H2Dialect
  # DB
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: ODMNOTIFICATION
    locations: classpath:db/migration/h2
    clean-on-validation-error: true

##########################
# Other configuration
##########################
blindata:
  url: http://localhost:3000
  user: "owner"
  password: "owner123"
  tenantUUID: "fc8dbadb-83b9-4c4a-baec-fc5a5f91f98b"
  roleUuid: "777f0307-bf30-4f70-92a4-f0cf3bc3f436"

odm:
  productPlane:
    policyService:
      active: true
      address: http://localhost:8005
