##########################
# Server configuration
##########################
server:
  port: 9002
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/metaservice/

############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  profile: testpostgresql
  jpa:
    hibernate:
      ddl-auto: validate
      #show-sql: true
      naming:
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # Or PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: ODMNOTIFICATION
  datasource:
    # TestContainer URL for auto-creation of Docker PostgreSQL DB on app start-up
    # https://java.testcontainers.org/modules/databases/jdbc/
    # Create a Docker container from postgresql:11-alpine image
    url: jdbc:tc:postgresql:11-alpine:///odmpdb?stringtype=unspecified&TC_REUSABLE=true
    # TestContainers driverClassName for JDBC url generated DBs
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: postgres
    password: my-secret-password
  flyway:
    # Redundant (Flyway get them from datasource) + conflicts with TestContainers DBs from JDBC url auto-generation integration with FLyway
    # https://stackoverflow.com/questions/73605371/table-not-found-in-integration-tests-when-using-testcontainers-with-flyway
    #url: jdbc:mysql://localhost:3306/odmpdb
    user: postgres
    password: my-secret-password
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: ODMNOTIFICATION
    locations: classpath:db/migration/postgresql
    clean-on-validation-error: true

##########################
# Other configuration
##########################
blindata:
  url: http://localhost:3000
  user: "owner"
  password: "owner123"
  tenantUUID: "fc8dbadb-83b9-4c4a-baec-fc5a5f91f98b"
  roleUuid: "777f0307-bf30-4f70-92a4-f0cf3bc3f436"
