package org.opendatamesh.platform.pp.notification.api.resources.v2;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.core.commons.resources.utils.TimestampedResource;
import org.opendatamesh.platform.pp.notification.api.resources.v2.enums.EventV2NotificationStatus;

@JsonIgnoreProperties(ignoreUnknown = true)
public class EventV2NotificationResource extends TimestampedResource implements Cloneable {
    @Schema(description = "Unique identifier of the notification (autogenerated sequence ID)", example = "101")
    private Long sequenceId;

    @Schema(description = "Current status of the notification", example = "DELIVERED")
    private EventV2NotificationStatus status;

    @Schema(description = "Event associated with this notification")
    private EventV2Resource event;

    @Schema(description = "Subscription that triggered this notification")
    private EventV2SubscriptionResource subscription;

    @Schema(description = "Error message if notification delivery failed", example = "Connection timeout while reaching observer server")
    private String errorMessage;

    public EventV2NotificationResource() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public EventV2NotificationStatus getStatus() {
        return status;
    }

    public void setStatus(EventV2NotificationStatus status) {
        this.status = status;
    }

    public EventV2Resource getEvent() {
        return event;
    }

    public void setEvent(EventV2Resource event) {
        this.event = event;
    }

    public EventV2SubscriptionResource getSubscription() {
        return subscription;
    }

    public void setSubscription(EventV2SubscriptionResource subscription) {
        this.subscription = subscription;
    }

    public String getErrorMessage() {
        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }
}