package org.opendatamesh.platform.pp.notification.api.resources.v2;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.JsonNode;
import io.swagger.v3.oas.annotations.media.Schema;
import org.opendatamesh.platform.core.commons.resources.utils.TimestampedResource;
import org.opendatamesh.platform.pp.notification.api.resources.v2.enums.EventV2EventType;
import org.opendatamesh.platform.pp.notification.api.resources.v2.enums.EventV2EventTypeVersion;
import org.opendatamesh.platform.pp.notification.api.resources.v2.enums.EventV2ResourceType;

@JsonIgnoreProperties(ignoreUnknown = true)
public class EventV2Resource extends TimestampedResource {
    @Schema(description = "Unique identifier of the event (autogenerated sequence ID)", example = "42")
    private Long sequenceId;

    @Schema(description = "Type of the resource that generated the event", example = "DATA_PRODUCT")
    private EventV2ResourceType resourceType;

    @Schema(description = "Identifier of the resource that generated the event", example = "d5b5b9ac-6a73-4c73-b9ce-4bfc10a1dba0")
    private String resourceIdentifier;

    @Schema(description = "Type of event emitted")
    private EventV2EventType type;

    @Schema(description = "Version of the event type definition", example = "1.0.0")
    private EventV2EventTypeVersion eventTypeVersion;

    @Schema(description = "JSON content of the event")
    private JsonNode eventContent;

    public EventV2Resource() {
    }

    public Long getSequenceId() {
        return sequenceId;
    }

    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    public EventV2ResourceType getResourceType() {
        return resourceType;
    }

    public void setResourceType(EventV2ResourceType resourceType) {
        this.resourceType = resourceType;
    }

    public String getResourceIdentifier() {
        return resourceIdentifier;
    }

    public void setResourceIdentifier(String resourceIdentifier) {
        this.resourceIdentifier = resourceIdentifier;
    }

    public EventV2EventType getType() {
        return type;
    }

    public void setType(EventV2EventType type) {
        this.type = type;
    }

    public EventV2EventTypeVersion getEventTypeVersion() {
        return eventTypeVersion;
    }

    public void setEventTypeVersion(EventV2EventTypeVersion eventTypeVersion) {
        this.eventTypeVersion = eventTypeVersion;
    }

    public JsonNode getEventContent() {
        return eventContent;
    }

    public void setEventContent(JsonNode eventContent) {
        this.eventContent = eventContent;
    }
}
