ALTER TABLE ODMDEVOPS.TASKS
ADD COLUMN IF NOT EXISTS STARTED_BY_ACTIVITY BOOLEAN;

ALTER TABLE ODMDEVOPS.TASKS
ADD COLUMN IF NOT EXISTS TASK_NAME VARCHAR(255);

ALTER TABLE ODMDEVOPS.TASKS
ADD COLUMN IF NOT EXISTS DESCRIPTION text;