# MySql 5.7 Docker image
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'odmpdb'
      MYSQL_USER: 'odmp'
      MYSQL_PASSWORD: 'odmp'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - published: 3306
        target: 3306
    expose:
      - 3306
    #network_mode: "host"
version: '3.3'