##########################
# Server configuration
##########################
app:
  workdir:

server:
  error:
    include-message: always


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localpostgresql
  # JPA
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: validate #none
      naming:
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect # Or PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: ODMDEVOPS
  # DB
  datasource:
    url: jdbc:postgresql://localhost:5432/odmpdb
    username: postgres
    password: postgres
    #username: usr
    #password: pwd
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    #enabled: false # To disable
    url: jdbc:postgresql://localhost:5432/odmpdb
    user: postgres
    password: postgres
    #username: usr
    #password: pwd
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: flyway
    locations: classpath:db/migration/postgres
    clean-on-validation-error: true


odm:
  productPlane:
    registryService:
      active: true
      address: http://localhost:8001
    devopsService:
      active: true
      address: http://localhost:8002
    blueprintService:
      active: false
      address: http://localhost:8003
  utilityPlane:
    policyServices:
      open-policy-agent:
        active: false
        address: http://localhost:9001
    notificationServices:
      blindata:
        active: false
        address: http://localhost:9002
    executorServices:
      azure-devops:
        active: true
        address: http://localhost:9003
