-- see https://flywaydb.org/documentation/tutorials/repeatable

DROP VIEW IF EXISTS "TEST_VIEW";

CREATE VIEW "PUBLIC"."TEST_VIEW" AS
SELECT
    a."ID"
    , a."DESCRIPTION"
    , a."DOMAIN"
    , b."VERSION_NUMBER"
    , b."DESCRIPTION" AS "VERSION_DESCRIPTION"
FROM "PUBLIC"."DPDS_DATA_PRODUCTS" a
    INNER JOIN "PUBLIC"."DPDS_DATA_PRODUCT_VERSIONS" b
        ON a."ID" = b."DATA_PRODUCT_ID"
;