############################################
# Server configuration
############################################
app:
  workdir:

server:
  error:
    include-message: always


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localmysql
  # JPA
  jpa:
    hibernate:
      ddl-auto: none #validate #errors on scripts
      #show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/ODMPARAM?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    #enabled: false # To disable
    url: jdbc:mysql://localhost:3306/ODMPARAM
    user: "root"
    password: "root"
    locations: classpath:db/migration/mysql
    clean-on-validation-error: true


############################################
# Encryption settings
############################################
encryption:
  enabled: true
  acceptedClientUUID: paramclient123