-- Postgres 11;

CREATE SCHEMA IF NOT EXISTS "PUBLIC";
CREATE SEQUENCE "PUBLIC".HIBERNATE_SEQUENCE START WITH 1;


-- DATA_PRODUCTS

CREATE TABLE "PUBLIC"."DATA_PRODUCTS"(
    "ID"  VARCHAR(255) PRIMARY KEY,
    "FQN"  VARCHAR(255),
    "DOMAIN"  VARCHAR(255),
    "DESCRIPTION"  VARCHAR(255)
);


-- DATA PPRODUCT > VERSIONS

CREATE TABLE "PUBLIC"."DP_VERSIONS"(
    "DATA_PRODUCT_ID" CHARACTER VARYING(255) NOT NULL,
    "VERSION_NUMBER" CHARACTER VARYING(255) NOT NULL,

    "DP_FQN" CHARACTER VARYING(255),
    "DP_ENTITY_TYPE" CHARACTER VARYING(255),
    "DP_NAME" CHARACTER VARYING(255),
    "DP_DISPLAY_NAME" CHARACTER VARYING(255),
    "DP_DOMAIN" CHARACTER VARYING(255),

    "DESCRIPTION" CHARACTER VARYING(255),
    "OWNER_ID" CHARACTER VARYING(255) NOT NULL,
    "EXTERNAL_DOC_ID" BIGINT,
    
    "DPDS_VERSION" CHARACTER VARYING(255),
    "CONTENT" CHARACTER VARYING,    
    
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);
ALTER TABLE "PUBLIC"."DP_VERSIONS" ADD CONSTRAINT "DP_VERSIONS_PK" PRIMARY KEY ("DATA_PRODUCT_ID", "VERSION_NUMBER");


-- DATA PPRODUCT > VERSION > INFO_OWNERS

CREATE TABLE "PUBLIC"."DPV_INFO_OWNERS"(
    "ID"  VARCHAR(255) PRIMARY KEY,
    "NAME"  VARCHAR(255)
);


-- DATA PPRODUCT > VERSION > DPV_INFO_CONTACT_POINTS

CREATE TABLE "PUBLIC"."DPV_INFO_CONTACT_POINTS"(
    "DATA_PRODUCT_ID" CHARACTER VARYING(255) NOT NULL,
    "VERSION_NUMBER" CHARACTER VARYING(255) NOT NULL,
    "NAME" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "CHANNEL" CHARACTER VARYING(255),
    "ADDRESS" CHARACTER VARYING(255)
);


-- DATA PPRODUCT > VERSION > DPV_PORTS

CREATE TABLE "PUBLIC"."DPV_PORTS"(
    "DATA_PRODUCT_ID" CHARACTER VARYING(255),
    "DATA_PRODUCT_VERSION" CHARACTER VARYING(255),

    "ID" CHARACTER VARYING(255) PRIMARY KEY,
    "FQN" CHARACTER VARYING(255),
    "ENTITY_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "VERSION" CHARACTER VARYING(255),

    "DISPLAY_NAME" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
  
    "PROMISES_ID" BIGINT,
    "EXPECTATIONS_ID" BIGINT,
    "CONTRACTS_ID" BIGINT,
    
    "COMPONENT_GROUP" CHARACTER VARYING(255),
    "EXTERNAL_DOC_ID" BIGINT, 
    
    "CONTENT" CHARACTER VARYING,

    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);


-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENTS

CREATE TABLE "PUBLIC"."DPV_APP_COMPONENTS"(
    "DATA_PRODUCT_ID" CHARACTER VARYING(255),
    "DATA_PRODUCT_VERSION" CHARACTER VARYING(255),

    "ID" CHARACTER VARYING(255) PRIMARY KEY,
    "FQN" CHARACTER VARYING(255),
    "ENTITY_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "VERSION" CHARACTER VARYING(255),
    
    "DISPLAY_NAME" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    
    "PLATFORM" CHARACTER VARYING(255),
    "APPLICATION_TYPE" CHARACTER VARYING(255),

    "BUILD_INFO_ID" BIGINT,
    "DEPLOY_INFO_ID" BIGINT,
    
    "COMPONENT_GROUP" CHARACTER VARYING(255),
    "EXTERNAL_DOC_ID" BIGINT,
   
    "CONTENT" CHARACTER VARYING,
     
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);

-- DATA PPRODUCT > VERSION > DPV_APP_COMPONENT_DEPENDENCIES

CREATE MEMORY TABLE "PUBLIC"."DPV_APP_COMPONENT_DEPENDENCIES"(
    "COMPONENT_ID" CHARACTER VARYING(255) NOT NULL,
    "DEPENDS_ON_COMPONENT_ID" CHARACTER VARYING(255)
);


-- DATA PPRODUCT > VERSION > DPV_INFRA_COMPONENTS

CREATE TABLE "PUBLIC"."DPV_INFRA_COMPONENTS"(
    "DATA_PRODUCT_ID" CHARACTER VARYING(255),    
    "DATA_PRODUCT_VERSION" CHARACTER VARYING(255),

    "ID" CHARACTER VARYING(255) PRIMARY KEY,
    "FQN" CHARACTER VARYING(255),
    "ENTITY_TYPE" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "VERSION" CHARACTER VARYING(255),
    
    "DISPLAY_NAME" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    
    "PLATFORM" CHARACTER VARYING(255),
    "INFRASTRUCTURE_TYPE" CHARACTER VARYING(255),
    
    "PROVISION_INFO_ID" BIGINT,
    
    "COMPONENT_GROUP" CHARACTER VARYING(255),
    "EXTERNAL_DOC_ID" BIGINT,

    "CONTENT" CHARACTER VARYING,
    
    "CREATED_AT" TIMESTAMP,
    "UPDATED_AT" TIMESTAMP
);

-- DATA PPRODUCT > VERSION > DPV_INFRA_COMPONENT_DEPENDENCIES

CREATE TABLE "PUBLIC"."DPV_INFRA_COMPONENT_DEPENDENCIES"(
    "COMPONENT_ID" CHARACTER VARYING(255) NOT NULL,
    "DEPENDS_ON_COMPONENT_ID" CHARACTER VARYING(255)
);






CREATE TABLE "PUBLIC"."DPDS_APP_COMPONENT_BUILD_INFOS"(
    "ID" BIGINT PRIMARY KEY,
    "CONFIGURATIONS" VARCHAR(5000),
    "SERVICE_ID" BIGINT,
    "TEMPLATE_ID" BIGINT
);



CREATE TABLE "PUBLIC"."DPDS_APP_COMPONENT_DEPLOY_INFOS"(
    "ID" BIGINT PRIMARY KEY,
    "CONFIGURATIONS"  VARCHAR(5000),
    "SERVICE_ID" BIGINT,
    "TEMPLATE_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_APP_COMPONENT_SINKS"(
    "ID"  VARCHAR(255) NOT NULL,
    "SINK_ID"  VARCHAR(255)
);

CREATE TABLE "PUBLIC"."DPDS_APP_COMPONENT_SOURCES"(
    "ID"  VARCHAR(255) NOT NULL,
    "SOURCE_ID"  VARCHAR(255)
);

CREATE TABLE "PUBLIC"."DPDS_APP_COMPONENT_TAGS"(
    "ID"  VARCHAR(255) NOT NULL,
    "TAG_ID"  VARCHAR(255)
);



CREATE TABLE "PUBLIC"."DPDS_DATA_PRODUCT_TAGS"(
    "DATAPRODUCT_ID"  VARCHAR(255) NOT NULL,
    "VERSION"  VARCHAR(255) NOT NULL,
    "TAG_ID"  VARCHAR(255)
);




CREATE TABLE "PUBLIC"."DPDS_EXTERNAL_RESOURCES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "DESCRIPTION"  VARCHAR(255),
    "HREF"  VARCHAR(255),
    "MEDIA_TYPE"  VARCHAR(255)
);







CREATE TABLE "PUBLIC"."DPDS_INFRA_COMPONENT_TAGS"(
    "ID"  VARCHAR(255) NOT NULL,
    "TAG_ID"  VARCHAR(255)
);



CREATE TABLE "PUBLIC"."DPDS_INFRA_PROVISION_INFOS"(
    "ID" BIGINT PRIMARY KEY,
    "CONFIGURATIONS"  VARCHAR(5000),
    "SERVICE_ID" BIGINT,
    "TEMPLATE_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_PORT_CONTRACTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "BILLING_POLICY_ID" BIGINT,
    "SLA_ID" BIGINT,
    "TERMS_AND_CONDITIONS_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_PORT_EXPECTATIONS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "AUDIENCE_ID" BIGINT,
    "USAGE_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_PORT_PROMISES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "API_ID" BIGINT,
    "PLATFORM"  VARCHAR(255),
    "SERVICE_TYPE"  VARCHAR(255),
    "DEPRECTAION_POLICY_ID" BIGINT,
    "SLO_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_PORT_TAGS"(
    "ID"  VARCHAR(255) NOT NULL,
    "TAG_ID"  VARCHAR(255)
);



CREATE TABLE "PUBLIC"."DPDS_REFERENCE_OBJECTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "DESCRIPTION"  VARCHAR(255),
    "ORIGINAL_REF"  VARCHAR(255),
    "CONTENT"  VARCHAR,
    "REF"  VARCHAR(255)
);

CREATE TABLE "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "DESCRIPTION"  VARCHAR(255),
    "EXTERNAL_DOC_ID" BIGINT
);

CREATE TABLE "PUBLIC"."DPDS_STANDARD_DEFINITIONS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "NAME"  VARCHAR(255),
    "VERSION"  VARCHAR(50),
    "DESCRIPTION"  VARCHAR(255),
    "SPECIFICATION"  VARCHAR(255),
    "SPECIFICATION_VERSION"  VARCHAR(50),
    "DEFINITION_ID" BIGINT, -- FK on DPDS_EXTERNAL_RESOURCES(ID)
    "EXTERNAL_DOC_ID" BIGINT -- FK on DPDS_REFERENCE_OBJECTS(ID)
);

CREATE TABLE "PUBLIC"."DPDS_DEFINITIONS"(
    "ID"  BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "NAME"  VARCHAR(255),
    "VERSION"  VARCHAR(50),
    "STATUS"  VARCHAR(125),
    "DISPLAY_NAME"  VARCHAR(255),
    "DESCRIPTION"  VARCHAR(255),
    "TYPE"  VARCHAR(255),
    "SPECIFICATION"  VARCHAR(255),
    "SPECIFICATION_VERSION"  VARCHAR(50),
    "CONTENT_MEDIA_TYPE"  VARCHAR(255),
    "CONTENT"  VARCHAR
);

CREATE TABLE "PUBLIC"."DPDS_TEMPLATE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "DESCRIPTION"  VARCHAR(255),
    "HREF"  VARCHAR(255),
    "MEDIA_TYPE"  VARCHAR(255)
);

CREATE TABLE "PUBLIC"."DPDS_COMPONENT_TEMPLATE"(
    "COMPONENT_ID" BIGINT NOT NULL,
    "TEMPLATE_ID" BIGINT NOT NULL,
    "COMPONENT_TYPE" VARCHAR(255) NOT NULL,
    "INFO_TYPE" VARCHAR(255) NOT NULL
)
ALTER TABLE "PUBLIC"."DPDS_COMPONENT_TEMPLATE" ADD CONSTRAINT "DPDS_COMPONENT_TEMPLATE_PK" PRIMARY KEY ("COMPONENT_ID", "TEMPLATE_ID", "COMPONENT_TYPE", "INFO_TYPE");


CREATE TABLE "PUBLIC"."DPDS_SCHEMAS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
    "NAME"  VARCHAR(255),
    "VERSION"  VARCHAR(50),
    "MEDIA_TYPE"  VARCHAR(255),
    "CONTENT" VARCHAR 
);
CREATE TABLE "PUBLIC"."DPDS_API_TO_SCHEMA_RELATIONSHIPS"(
    "API_ID" BIGINT NOT NULL,
    "SCHEMA_ID" BIGINT NOT NULL,
    "OPERATION_ID" VARCHAR(255),
    "OUTPUT_MEDIA_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."DPDS_API_TO_SCHEMA_RELATIONSHIPS" ADD CONSTRAINT "DPDS_API_TO_SCHEMA_RELATIONSHIPS_PK" PRIMARY KEY ("API_ID", "SCHEMA_ID");

-- TODO ADD FK






-- DP_VERSIONS FKs

ALTER TABLE "PUBLIC"."DP_VERSIONS" ADD CONSTRAINT "PUBLIC"."C_FK1__DP_VERSIONS" FOREIGN KEY("OWNER_ID") REFERENCES "PUBLIC"."DPV_INFO_OWNERS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DP_VERSIONS" ADD CONSTRAINT "PUBLIC"."C_FK2_DP_VERSIONS" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPV_INFO_CONTACT_POINTS" ADD CONSTRAINT "PUBLIC"."C_FK_DPV_INFO_CONTACT_POINTS" FOREIGN KEY("DATA_PRODUCT_ID", "VERSION_NUMBER") REFERENCES "PUBLIC"."DP_VERSIONS"("DATA_PRODUCT_ID", "VERSION_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_DATA_PRODUCT_TAGS" ADD CONSTRAINT "PUBLIC"."C_FK_DATA_PRODUCT_TAGS" FOREIGN KEY("DATAPRODUCT_ID", "VERSION") REFERENCES "PUBLIC"."DP_VERSIONS"("DATA_PRODUCT_ID", "VERSION_NUMBER") NOCHECK;

-- DPV_PORTS FKs

ALTER TABLE "PUBLIC"."DPV_PORTS" ADD CONSTRAINT "PUBLIC"."C_FK1_DPV_PORTS" FOREIGN KEY("DATA_PRODUCT_ID", "DATA_PRODUCT_VERSION") REFERENCES "PUBLIC"."DP_VERSIONS"("DATA_PRODUCT_ID", "VERSION_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_PORTS" ADD CONSTRAINT "PUBLIC"."C_FK2_DPV_PORTS" FOREIGN KEY("PROMISES_ID") REFERENCES "PUBLIC"."DPDS_PORT_PROMISES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_PORTS" ADD CONSTRAINT "PUBLIC"."C_FK3_DPV_PORTS" FOREIGN KEY("EXPECTATIONS_ID") REFERENCES "PUBLIC"."DPDS_PORT_EXPECTATIONS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_PORTS" ADD CONSTRAINT "PUBLIC"."C_FK4_DPV_PORTS" FOREIGN KEY("CONTRACTS_ID") REFERENCES "PUBLIC"."DPDS_PORT_CONTRACTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_PORTS" ADD CONSTRAINT "PUBLIC"."C_FK5_DPV_PORTS" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_PORT_TAGS" ADD CONSTRAINT "PUBLIC"."FKSXD77OQ8WIO381WHOJWICLXLG" FOREIGN KEY("ID") REFERENCES "PUBLIC"."DPV_PORTS"("ID") NOCHECK;


-- DPV_APP_COMPONENTS FKs

ALTER TABLE "PUBLIC"."DPV_APP_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK1_DPV_APP_COMPONENTS" FOREIGN KEY("DATA_PRODUCT_ID", "DATA_PRODUCT_VERSION") REFERENCES "PUBLIC"."DP_VERSIONS"("DATA_PRODUCT_ID", "VERSION_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_APP_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK2_DPV_APP_COMPONENTS" FOREIGN KEY("BUILD_INFO_ID") REFERENCES "PUBLIC"."DPDS_APP_COMPONENT_BUILD_INFOS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_APP_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK3_DPV_APP_COMPONENTS" FOREIGN KEY("DEPLOY_INFO_ID") REFERENCES "PUBLIC"."DPDS_APP_COMPONENT_DEPLOY_INFOS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_APP_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK4_DPV_APP_COMPONENTS" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER  TABLE"PUBLIC"."DPDS_APP_COMPONENT_TAGS" ADD CONSTRAINT "PUBLIC"."FKSQ1G1IFWKXGV440A0HOKR1LEU" FOREIGN KEY("ID") REFERENCES "PUBLIC"."DPV_APP_COMPONENTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_APP_COMPONENT_DEPENDENCIES" ADD CONSTRAINT "PUBLIC"."C_FK_DPV_APP_COMPONENT_DEPENDENCIES" FOREIGN KEY("COMPONENT_ID") REFERENCES "PUBLIC"."DPV_APP_COMPONENTS"("ID") NOCHECK;

-- DPDS_INFRA_COMPONENTS FKs

ALTER TABLE "PUBLIC"."DPV_INFRA_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK1_DPV_INFRA_COMPONENTS" FOREIGN KEY("DATA_PRODUCT_ID", "DATA_PRODUCT_VERSION") REFERENCES "PUBLIC"."DP_VERSIONS"("DATA_PRODUCT_ID", "VERSION_NUMBER") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_INFRA_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK2_DPV_INFRA_COMPONENTS" FOREIGN KEY("PROVISION_INFO_ID") REFERENCES "PUBLIC"."DPDS_INFRA_PROVISION_INFOS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_INFRA_COMPONENTS" ADD CONSTRAINT "PUBLIC"."C_FK3_DPV_INFRA_COMPONENTS" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_INFRA_COMPONENT_TAGS" ADD CONSTRAINT "PUBLIC"."FKOGCUHXRVBR8TRJSNF1SCFJK0D" FOREIGN KEY("ID") REFERENCES "PUBLIC"."DPV_INFRA_COMPONENTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPV_INFRA_COMPONENT_DEPENDENCIES" ADD CONSTRAINT "PUBLIC"."C_FK_DPV_INFRA_COMPONENT_DEPENDENCIES" FOREIGN KEY("COMPONENT_ID") REFERENCES "PUBLIC"."DPV_INFRA_COMPONENTS"("ID") NOCHECK;






-- TODOs


ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_SINKS" ADD CONSTRAINT "PUBLIC"."FKQE422CLVRRG8J0GXLDRV4IW6V" FOREIGN KEY("ID") REFERENCES "PUBLIC"."DPV_APP_COMPONENTS"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_SOURCES" ADD CONSTRAINT "PUBLIC"."FKR33DO8116KIGTE5LYMDB8I1TP" FOREIGN KEY("ID") REFERENCES "PUBLIC"."DPV_APP_COMPONENTS"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_PORT_EXPECTATIONS" ADD CONSTRAINT "PUBLIC"."FK6OUWT8NGHLS5VGDJMJGNHW76T" FOREIGN KEY("AUDIENCE_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_PORT_PROMISES" ADD CONSTRAINT "PUBLIC"."FKWP3UH6EAAQGP6G9L2E54J8S3" FOREIGN KEY("SLO_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_PORT_PROMISES" ADD CONSTRAINT "PUBLIC"."FKTDT2R73RTCJ1SN6GIIQY3G3RP" FOREIGN KEY("DEPRECTAION_POLICY_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS" ADD CONSTRAINT "PUBLIC"."FK9FJQQ2L7NR7TAXI81TU5J4LBW" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_PORT_EXPECTATIONS" ADD CONSTRAINT "PUBLIC"."FK47C01XXKCY2X9N9QOY3EK0JLD" FOREIGN KEY("USAGE_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_STANDARD_DEFINITIONS" ADD CONSTRAINT "PUBLIC"."FKN28C6VYQCY0S460D5WB2VO4R0" FOREIGN KEY("EXTERNAL_DOC_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_BUILD_INFOS" ADD CONSTRAINT "PUBLIC"."FKA97KW9AILVD4E74LC7TJXNDGL" FOREIGN KEY("SERVICE_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_INFRA_PROVISION_INFOS" ADD CONSTRAINT "PUBLIC"."FKM7I22E0X3P84YSYUC0525LGC0" FOREIGN KEY("TEMPLATE_ID") REFERENCES "PUBLIC"."DPDS_REFERENCE_OBJECTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_PORT_CONTRACTS" ADD CONSTRAINT "PUBLIC"."FK9DAAXC2S6VM3M6G30EV1F0U8S" FOREIGN KEY("SLA_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_BUILD_INFOS" ADD CONSTRAINT "PUBLIC"."FKLU60VQDNDN350990MQ19DAAIF" FOREIGN KEY("TEMPLATE_ID") REFERENCES "PUBLIC"."DPDS_REFERENCE_OBJECTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_INFRA_PROVISION_INFOS" ADD CONSTRAINT "PUBLIC"."FKOEXPXBDNEG1J0K1252FLJGR0D" FOREIGN KEY("SERVICE_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_STANDARD_DEFINITIONS" ADD CONSTRAINT "PUBLIC"."FKRKJVHRTXR6P31WQBO399FCE26" FOREIGN KEY("DEFINITION_ID") REFERENCES "PUBLIC"."DPDS_REFERENCE_OBJECTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_PORT_CONTRACTS" ADD CONSTRAINT "PUBLIC"."FKR2XMY5Q0CTMMQ301KNVHVFQH8" FOREIGN KEY("BILLING_POLICY_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;


ALTER TABLE "PUBLIC"."DPDS_PORT_CONTRACTS" ADD CONSTRAINT "PUBLIC"."FK48OOYF319R9RSVKK9FRW4X7GG" FOREIGN KEY("TERMS_AND_CONDITIONS_ID") REFERENCES "PUBLIC"."DPDS_SPEC_EXTENSION_POINTS"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_DEPLOY_INFOS" ADD CONSTRAINT "PUBLIC"."FKTPC0GAMBVQKQK8E3DKRW8R24A" FOREIGN KEY("TEMPLATE_ID") REFERENCES "PUBLIC"."DPDS_REFERENCE_OBJECTS"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_APP_COMPONENT_DEPLOY_INFOS" ADD CONSTRAINT "PUBLIC"."FK8VI9YWFKJOOYEL3URUJICOOK9" FOREIGN KEY("SERVICE_ID") REFERENCES "PUBLIC"."DPDS_EXTERNAL_RESOURCES"("ID") NOCHECK;

ALTER TABLE "PUBLIC"."DPDS_COMPONENT_TEMPLATE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DPDS_COMPONENT_TEMPLATE_FK1" FOREIGN KEY("TEMPLATE_ID") REFERENCES "PUBLIC"."DPDS_TEMPLATE"("ID") NOCHECK;