##########################
# Active profile
##########################
spring:
  profiles:
    active: dev 
    #testmysql 
    #testpostgresql

server:
  port: 8001
  servlet:
    context-path: /api/v1/pp/registry/

##########################
# Logging configuration
##########################
logging:
  level:
    org:
      apache:
        http: INFO
      opendatamesh:
        dpexperience:
          api.*: DEBUG
    httpclient:
      wire: INFO
    it:
      quantyca:
        odm:
          api:
            planes:
              dpexperience.*: DEBUG


##########################
# Doc configuration
##########################
springdoc:
  swagger-ui:
    operationsSorter: alpha


##########################
# Registry configurations
##########################
policyserviceaddress: http://localhost:9001
metaserviceaddress: http://localhost:9002
skippolicyservice: true
skipmetaservice: true






