##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: /api/v1/pp/


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localpostgres
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate #none
      naming:
        #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect # Or PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: PUBLIC
  # DB
  datasource:
    # TestContainer URL for auto-creation of Docker PostgreSQL DB on app start-up
    # https://java.testcontainers.org/modules/databases/jdbc/
    # Create a Docker container from postgresql:11-alpine image
    url: jdbc:tc:postgresql:11-alpine:///odmpdb?stringtype=unspecified
    username: postgres
    password: postgres
    # TestContainers driverClassName for JDBC url generated DBs
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    # Redundant (Flyway get them from datasource) + conflicts with TestContainers DBs from JDBC url auto-generation integration with FLyway
    # https://stackoverflow.com/questions/73605371/table-not-found-in-integration-tests-when-using-testcontainers-with-flyway
    #url: jdbc:postgresql://localhost:5432/odmpdb
    #user: postgres
    #password: postgres
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: flyway
    locations: classpath:db/migration/postgres
    clean-on-validation-error: true


##############################
# Policy Module configuration
##############################
policyserviceaddress: http://localhost:4242
metaserviceaddress: http://localhost:8084

skippolicyservice: true
skipmetaservice: true