##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: /api/v1/pp/


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localpostgres
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect # Or PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: PUBLIC
  # DB
  datasource:
    url: jdbc:postgresql://localhost:5432/odmpdb
    username: usr
    password: pwd
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    #enabled: false # To disable
    url: jdbc:postgresql://localhost:5432/odmpdb
    user: usr
    password: pwd
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: flyway
    locations: classpath:db/migration/postgres
    clean-on-validation-error: true


##############################
# Policy Module configuration
##############################
policyserviceaddress: http://localhost:4242
metaserviceaddress: http://localhost:8084

skippolicyservice: true
skipmetaservice: true