##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 8585
  error:
    include-message: always
  servlet:
    context-path: /api/v1/pp/


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localmysql
  # JPA
  jpa:
    hibernate:
      ddl-auto: none #validate #errors on scripts
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  # DB
  datasource:
    # TestContainer URL for auto-creation of Docker PostgreSQL DB on app start-up
    # https://java.testcontainers.org/modules/databases/jdbc/
    # Create a Docker container from mysql:8.0.24 image
    url: jdbc:tc:mysql:8.0.24://localhost/PUBLIC?user=root&password=root&currentSchema=PUBLIC
    # OBS: without localhost/ it fails to create PUBLIC DB/Schema (it use default db-schema "test"
    # and without user and password it use "test" "test"
    # TestContainers driverClassName for JDBC url generated DBs
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    #driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    #url: jdbc:mysql://localhost:3306/odmpdb
    #user: "root"
    #password: "root"
    locations: classpath:db/migration/mysql
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    #schemas: flyway # not working
    clean-on-validation-error: true


##############################
# Policy Module configuration
##############################
policyserviceaddress: http://localhost:4242
metaserviceaddress: http://localhost:8084

skippolicyservice: true
skipmetaservice: true