##########################
# Server configuration
##########################
app:
  workdir:

server:
  error:
    include-message: always


############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: localmysql
  # JPA
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: none #errors on scripts --> MySql + Hibernate validation want TEXT as VARCHAR(N)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/ODMREGISTRY?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    #enabled: false # To disable
    url: jdbc:mysql://localhost:3306/ODMREGISTRY
    user: "root"
    password: "root"
    locations: classpath:db/migration/mysql
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    #schemas: flyway # not working
    clean-on-validation-error: true

#############################
# ODM projects configurations
#############################
odm:
  schemas:
    validation:
      baseUrl: "https://raw.githubusercontent.com/opendatamesh-initiative/odm-specification-dpdescriptor/main/schemas/"
      supportedVersions:
        min: "1.0.0"
        max: null
  productPlane:
    policyService:
      active: false
      address: http://localhost:8005
    notificationService:
      active: false
      address: http://localhost:8006
