-- MySql 8;

CREATE TABLE hibernate_sequence (
    NEXT_VAL BIGINT AUTO_INCREMENT,
    PRIMARY KEY (NEXT_VAL)
);
INSERT INTO hibernate_sequence VALUES (0);

-- ENTITIES ============================================================================================================

-- POLICY_ENGINES ------------------------------------------------------------------------------------------------------
CREATE TABLE POLICY_ENGINES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    DISPLAY_NAME VARCHAR(255),
    ADAPTER_URL VARCHAR(1000),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    PRIMARY KEY(ID)
) ENGINE=InnoDB;

-- POLICIES ------------------------------------------------------------------------------------------------------------
CREATE TABLE POLICIES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    ROOT_ID BIGINT NOT NULL,
    NAME VARCHAR(255),
    DISPLAY_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    BLOCKING_FLAG TINYINT(1),
    SUITE VARCHAR(255), -- fase, tag, ...
    RAW_CONTENT TEXT,
    IS_LAST_VERSION TINYINT(1),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    POLICY_ENGINE_ID BIGINT NOT NULL,

    PRIMARY KEY(ID)
) ENGINE=InnoDB;

-- POLICY_EVALUATION_RESULTS
CREATE TABLE POLICY_EVALUATION_RESULTS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    DATA_PRODUCT_ID VARCHAR(255),
    DATA_PRODUCT_VERSION VARCHAR(255),
    POLICY_ID BIGINT NOT NULL,
    INPUT_OBJECT TEXT,
    OUTPUT_OBJECT TEXT,
    RESULT BOOLEAN,
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    PRIMARY KEY(ID)
) ENGINE=InnoDB;


-- FOREING KEYS ========================================================================================================

-- POLICIES FKs
ALTER TABLE POLICIES ADD CONSTRAINT C_FK1__POLICIES FOREIGN KEY(POLICY_ENGINE_ID) REFERENCES POLICY_ENGINES(ID) ON DELETE NO ACTION;

-- POLICY_EVALUATION_RESULTS FKs
ALTER TABLE POLICY_EVALUATION_RESULTS ADD CONSTRAINT C_FK1__POLICY_EVALUATION_RESULTS FOREIGN KEY(POLICY_ID) REFERENCES POLICIES(ID) ON DELETE CASCADE;
