-- Drop the existing foreign key constraint
ALTER TABLE "ODMPOLICY"."POLICIES" DROP CONSTRAINT IF EXISTS "C_FK1__POLICIES";

-- Recreate the foreign key constraint with CASCADE delete
ALTER TABLE "ODMPOLICY"."POLICIES" 
ADD CONSTRAINT "C_FK1__POLICIES" 
FOREIGN KEY("POLICY_ENGINE_ID") 
REFERENCES "ODMPOLICY"."POLICY_ENGINES"("ID") 
ON DELETE CASCADE;
