############################################
# Server configuration
############################################
app:
  workdir:

server:
  error:
    include-message: always


############################################
# Spring configurations
############################################
spring:
  # JPA configuration
  jpa:
    #show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        #format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: ODMBLUEPRINT
    database-platform: org.hibernate.dialect.H2Dialect
  # DB
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    #enabled: false # To disable
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: ODMBLUEPRINT
    locations: classpath:db/migration/h2
    clean-on-validation-error: true


############################################
# Git configurations
############################################
git:
  provider: "GITHUB"
  templates:
    path: "templates"
  oauth2:
    client:
      provider:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://github.com/api/v3/user
      registration:
        client-id: S{OUATH_CLIENT_ID}
        client-secret: ${OAUTH_CLIENT_SECRET}
        scope: repo
        authorization-grant-type: client_credentials