-- MySql 8;

CREATE TABLE hibernate_sequence (
    NEXT_VAL BIGINT AUTO_INCREMENT,
    PRIMARY KEY (NEXT_VAL)
);
INSERT INTO hibernate_sequence VALUES (0);


-- BLUEPRINTS ============================================
CREATE TABLE BLUEPRINTS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    VERSION VARCHAR(32),
    DISPLAY_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    REPOSITORY_PROVIDER VARCHAR(32),
    REPOSITORY_BASE_URL VARCHAR(1000),
    BLUEPRINT_REPO VARCHAR(255),
    TARGET_REPO VARCHAR(255),
    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    PRIMARY KEY (ID)
);


-- BLUEPRINT CONFIGS =====================================
--CREATE TABLE BLUEPRINT_CONFIGS (
--	BLUEPRINT_ID BIGINT NOT NULL,
--	PARAMETER VARCHAR(255) NOT NULL,
--	PARAMETER_VALUE VARCHAR(255),

--	PRIMARY KEY (BLUEPRINT_ID, PARAMETER)
--);
--ALTER TABLE BLUEPRINT_CONFIGS ADD CONSTRAINT C_FK_BLUEPRINT_CONFIGS FOREIGN KEY(BLUEPRINT_ID) REFERENCES BLUEPRINTS(ID) ON DELETE CASCADE;