# Postgres 11 Docker image
services:
  postgres:
    environment:
      POSTGRES_DB: odmpdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:rw
version: '3.3'
volumes:
  postgres: