############################################
# Spring, JPA, DB and Flyway configurations
############################################
spring:
  # Profile
  profile: testpostgresql
  # JPA
  jpa:
    hibernate:
      ddl-auto: none #validate #errors on scripts
      #show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect # Or PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: ODMPOLICY
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
  # DB
  datasource:
    # TestContainer URL for auto-creation of Docker PostgreSQL DB on app start-up
    # https://java.testcontainers.org/modules/databases/jdbc/
    # Create a Docker container from postgresql:11-alpine image
    url: jdbc:tc:postgresql:11-alpine:///odmpdb?stringtype=unspecified&TC_REUSABLE=true
    # TestContainers driverClassName for JDBC url generated DBs
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: usr
    password: pwd
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    # Redundant (Flyway get them from datasource) + conflicts with TestContainers DBs from JDBC url auto-generation integration with FLyway
    # https://stackoverflow.com/questions/73605371/table-not-found-in-integration-tests-when-using-testcontainers-with-flyway
    #url: jdbc:mysql://localhost:3306/odmpdb
    #user: "root"
    #password: "root"
    locations: classpath:db/migration/postgresql
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: ODMPOLICY
    clean-on-validation-error: true


##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 9001
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/policy-service/
timeout:
  seconds: 30


##########################
# OPA configuration
##########################
opa:
  url:
    policies: http://localhost:8181/v1/policies
    data: http://localhost:8181/v1/data