##########################
# Spring, JPA and Postgresql configuration
##########################
spring:
   profile: localpostgresql
   jpa:
      hibernate:
         ddl-auto: validate #none
         show-sql: true
         naming:
            #implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            globally_quoted_identifiers: true
            default_schema: ODMPOLICY
   datasource:
      url: jdbc:postgresql://localhost:5432/odmpdb #5433:mydb
      username: postgres #usr
      password: postgres #pwd
   h2:
      console:
         enabled: false
   flyway:
      #enabled: false # To disable
      url: jdbc:postgresql://localhost:5432/odmpdb #5433:mydb
      user: postgres #usr
      password: postgres #pwd
      #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
      schemas: ODMPOLICY
      locations: classpath:db/migration/postgresql
      clean-on-validation-error: true
# Uncomment the following properties if the first time you want to create and populate tables with schema.sql and data.sql
#spring.jpa.hibernate.ddl-auto: none
#spring.sql.init.mode: always

##########################
# Server configuration
##########################
server:
   port: 9001
   servlet:
      contextPath: /api/v1/planes/utility/policy-services/opa
   error:
      include-stacktrace: always
      include-message: always
timeout.seconds :  30

##########################
# OPA configuration
##########################
opa:
   url:
      policies: http://localhost:8181/v1/policies
      data: http://localhost:8181/v1/data