package org.opendatamesh.platform.pp.policy.server.resources.notificationservice;

public enum NotificationEventType {
    DATA_PRODUCT_CREATED,
    DATA_PRODUCT_UPDATED,
    DATA_PRODUCT_DELETED,
    DATA_PRODUCT_VERSION_CREATED,
    DATA_PRODUCT_VERSION_DELETED,

    DATA_PRODUCT_ACTIVITY_CREATED,
    DATA_PRODUCT_ACTIVITY_STARTED,
    DATA_PRODUCT_ACTIVITY_COMPLETED,
    DATA_PRODUCT_TASK_CREATED,
    DATA_PRODUCT_TASK_STARTED,
    DATA_PRODUCT_TASK_COMPLETED,

    POLICY_CREATED,
    POLICY_UPDATED,
    POLICY_DELETED
}
