name: odm-platform CI
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{secrets.SSH_KEY}}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
          #if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      #- name: Set up SSH Private Key
        #run: |
        #  mkdir -p /home/runner/.ssh
        #  echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/github_actions
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml