name: odm-platform CI
on:
  push:
    branches: # Execute on "main" branch and product branches, avoid others
      - 'main' # Main branch
      - '*.*' # Product branches (e.g., 0.7, 0.x, 1.x, ...)
  pull_request:
    branches:
      - 'main' # Main branch
      - '*.*' # Product branches (e.g., 0.7, 0.x, 1.x, ...)

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Execute tests with Maven
        run: |
          mvn -B test -Dspring.profiles.active=test
          mvn -B test -Dspring.profiles.active=testpostgresql
          mvn -B test -Dspring.profiles.active=testmysql
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
