name: odm-platform CI
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{secrets.SSH_KEY}}
      - name: Set up SSH Private Key
        #env:
        #  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        #run: |
        #  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        #  ssh-add - <<< "${{ secrets.SSH_KEY }}"
        #run: echo "${{ secrets.SSH_KEY }}" >> /home/.ssh/private_key.pub
        run: |
          ls /home
          ls /home/runner
      #- name: Set up JDK 11
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'
      #    distribution: 'temurin'
      #    cache: maven
      #- name: Build with Maven
      #  env:
      #    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      #  run: mvn -B clean install --file pom.xml