name: odm-platform CI/CD
on:
  push:
    tags:
      - '*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Set env
        run: echo "TAG_VERSION=$( echo ${{ github.ref_name }} | sed 's/[^0-9.]//g' )" >> $GITHUB_ENV
      - name: Update versions
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$TAG_VERSION
      - name: Push new version
        run: |
          git commit -am "Update version to $TAG_VERSION"
          git push
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn -DGitHubPackages=true deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
